### PR TITLE
update pointer error to compile on arm64

### PR DESCRIPTION
**Pull request by arnodelorme**

### CODE REVIEW

**Comment by chkothe** [comment]
It uses xml_ptr for most APIs, even though quite a number of them accept or return other objects (outlets, inlets); I guess as long as it's any type of pointer (even void*) it'll get past the compiler warnings/errors, but people editing this in the future may be thrown off by the wrong pointer type being used. Got time to touch that up?

**Comment by arnodelorme** [comment]
I only fixed changes that prevented compilation (I guess compilers have become more picky about incompatible pointer types, and the mex build does not have an option to ignore that—I looked). I would rather not dwell on that code further. Now I have the LSL library and MATLAB LSL mex wrappers recompiled for newer Macs and have the MATLAB app viewer working for Windows, older Intel Macs, and newer ARM Macs. It was laborious and painful. 

I actually wonder why you had to create Mex files. MATLAB can directly interface with C libraries like Python does with loadlibrary, so this would have been the more robust way to go to build the wrapper (but I agree mex files are convenient).

**Comment by chkothe** [comment]
Fair enough; so I'll merge that for now. It would be nice to make a new git release (last one is 1.14.0 from 2020 by @cboulay) that packages your new set of binaries so that users don't have to retrace your steps there.

As for why that was done that way, at the time I wasn't too fond of automated wrapper/interface generators, since C calling conventions can be messy and you don't want to find out 50 functions into a port that you need to start over using plain mex because the 51st function expects you do something with the return value that you can't do with callib(). It would have been worth a try, and maybe someone could investigate that and give it a shot if we want to reduce the maintenance burden on this for the next 10 years, but I had all the compile infrastructure on hand for BCILAB and knew mex well enough to pull it off pretty quickly.

**Comment by arnodelorme** [comment]
Yes, I can share my binary but @cboulay said he did not want it because it was not signed.

**Comment by cboulay** [comment]
It's only your liblsl.dylib that I don't want because if it's not signed then it'll create more errors than it'll solve. When the dylib isn't present, it's easier to detect and solve with `brew install labstreaminglayer/tap/lsl`.

**Comment by arnodelorme** [comment]
OK

**Pull request merged**
