### PR TITLE
FIX: build_mex error due to undeclared types

### PR DESCRIPTION
**Pull request by Vincentvjj**

### CODE REVIEW

**Comment by Vincentvjj** [comment]
@dmedine for some reason, the latest commit didn't work when I tried to build the mex files.

**Review by dmedine — COMMENTED** [review]
The changes to lsl_common.h are certainly necessary. Not sure why I was able to build on my system without them, but this would definitely cause problems with different compilers down the line. I will pull these in.

**Comment by dmedine** [comment]
Why did you close this PR? I think the additions are probably necessary.

**Comment by Vincentvjj** [comment]
I am encountering an error when I try to use the builded mex file. The internal error only happens when I call the set_postprocessing method. 

I was planning to reopen it once I am able to fix my errors..

**Comment by dmedine** [comment]
Ok.

This version (without the typedefs you added) works fine on my Windows 10, Matlab 15b using msvc141.

**Comment by Vincentvjj** [comment]
Have tested, it is working with the requirements stated in the comment above.

**Pull request merged**
